// <auto-generated />
using System;
using ElectronicHandyman.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronicHandyman.Domain.Migrations
{
    [DbContext(typeof(HandymanDbContext))]
    [Migration("20260502173709_SvgEntitiesAdd")]
    partial class SvgEntitiesAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaticUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardDocuments");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardFamilyId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyName")
                        .IsUnique();

                    b.ToTable("BoardFamilies");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Config.TexasInstrumentsApiConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TexasApiConfig");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.CircleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CenterX")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterY")
                        .HasColumnType("double precision");

                    b.Property<string>("FillType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.Property<string>("StrokeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StrokeWidth")
                        .HasColumnType("double precision");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AtAngle")
                        .HasColumnType("double precision");

                    b.Property<double>("AtX")
                        .HasColumnType("double precision");

                    b.Property<double>("AtY")
                        .HasColumnType("double precision");

                    b.Property<string>("ElectricalPinType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GraphicPinShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PolylineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FillType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrokeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StrokeWidth")
                        .HasColumnType("double precision");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.ToTable("Polylines");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PolylinePointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PolylineId")
                        .HasColumnType("integer");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PolylineId");

                    b.ToTable("PolylinePoints");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.RectangleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EndX")
                        .HasColumnType("double precision");

                    b.Property<double>("EndY")
                        .HasColumnType("double precision");

                    b.Property<string>("FillType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StartX")
                        .HasColumnType("double precision");

                    b.Property<double>("StartY")
                        .HasColumnType("double precision");

                    b.Property<string>("StrokeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StrokeWidth")
                        .HasColumnType("double precision");

                    b.Property<int>("SymbolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SymbolId");

                    b.ToTable("Rectangles");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardDocumentEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.BoardEntity", "Board")
                        .WithMany("Documents")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", "BoardFamily")
                        .WithMany("Boards")
                        .HasForeignKey("BoardFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardFamily");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.CircleEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", "Symbol")
                        .WithMany("Circles")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PinEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", "Symbol")
                        .WithMany("Pins")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PolylineEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", "Symbol")
                        .WithMany("Polylines")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PolylinePointEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.Kicad.PolylineEntity", "Polyline")
                        .WithMany("Points")
                        .HasForeignKey("PolylineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polyline");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.RectangleEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", "Symbol")
                        .WithMany("Rectangles")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.PolylineEntity", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.Kicad.SymbolEntity", b =>
                {
                    b.Navigation("Circles");

                    b.Navigation("Pins");

                    b.Navigation("Polylines");

                    b.Navigation("Rectangles");
                });
#pragma warning restore 612, 618
        }
    }
}
