// <auto-generated />
using ElectronicHandyman.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectronicHandyman.Domain.Migrations
{
    [DbContext(typeof(HandymanDbContext))]
    partial class HandymanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardDocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaticUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardDocumentEntity");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardFamilyId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamilyName")
                        .IsUnique();

                    b.ToTable("BoardFamilies");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardDocumentEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.BoardEntity", "Board")
                        .WithMany("Documents")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.HasOne("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", "BoardFamily")
                        .WithMany("Boards")
                        .HasForeignKey("BoardFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardFamily");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardEntity", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ElectronicHandyman.Domain.Domain.BoardFamilyEntity", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
